name: Build and Push clang-20-conan-aui-arm64

on:
  push:
    branches: [ "main" ]
    paths:
      - 'clang-20-conan-aui-arm64/**'
      - '.github/workflows/clang-20-conan-aui-arm64.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'clang-20-conan-aui-arm64/**'

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set lowercase repository owner
      run: |
        echo "REPOSITORY_OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push clang-20-conan-aui-arm64
      run: |
        docker build . --file clang-20-conan-aui-arm64/Dockerfile --tag ghcr.io/${{ env.REPOSITORY_OWNER_LC }}/clang-20-conan-aui-arm64:latest
        docker push ghcr.io/${{ env.REPOSITORY_OWNER_LC }}/clang-20-conan-aui-arm64:latest
