name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file clang-20-conan-aui/Dockerfile --tag clang-20-conan-aui:$(date +%s)
        docker build . --file gcc-15-conan-aui/Dockerfile --tag gcc-15-conan-aui:$(date +%s)
        docker build . --file NDK-28b-conan-aui/Dockerfile --tag ndk-28b-conan-aui:$(date +%s)
