name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image (clang-20-conan-aui)
      run: |
        docker build . --file clang-20-conan-aui/Dockerfile --tag ghcr.io/${{ github.repository_owner }}/clang-20-conan-aui:latest
        docker push ghcr.io/${{ github.repository_owner }}/clang-20-conan-aui:latest

    - name: Build the Docker image (gcc-15-conan-aui)
      run: |
        docker build . --file gcc-15-conan-aui/Dockerfile --tag ghcr.io/${{ github.repository_owner }}/gcc-15-conan-aui:latest
        docker push ghcr.io/${{ github.repository_owner }}/gcc-15-conan-aui:latest

    - name: Build the Docker image (ndk-28b-conan-aui)
      run: |
        docker build . --file NDK-28b-conan-aui/Dockerfile --tag ghcr.io/${{ github.repository_owner }}/ndk-28b-conan-aui:latest
        docker push ghcr.io/${{ github.repository_owner }}/ndk-28b-conan-aui:latest
